table delay_reasons

	column reason
		dataType: string
		summarizeBy: none
		sourceColumn: reason

	column events
		dataType: int64
		summarizeBy: sum
		sourceColumn: events

	measure 'Events (delay_reasons)' = SUM ( 'delay_reasons'[events] )
		formatString: #,0.00
		displayFolder: Measures
		/// Events for the 'Logged delay reasons' visual.

	partition delay_reasons = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExtractFolder & "\delay_reasons.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"reason", type text},
				        {"events", Int64.Type}
				    })
				in
				    Typed
