table reasons

	column Reason_Description
		dataType: string
		summarizeBy: none
		sourceColumn: Reason_Description

	column Reason_Category
		dataType: string
		summarizeBy: none
		sourceColumn: Reason_Category

	column appeals
		dataType: int64
		summarizeBy: sum
		sourceColumn: appeals

	column avg_tat
		dataType: double
		summarizeBy: sum
		sourceColumn: avg_tat

	column overturn_pct
		dataType: double
		summarizeBy: sum
		sourceColumn: overturn_pct

	partition reasons = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExtractFolder & "\reasons.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"Reason_Description", type text},
				        {"Reason_Category", type text},
				        {"appeals", Int64.Type},
				        {"avg_tat", type number},
				        {"overturn_pct", type number}
				    })
				in
				    Typed
