table rework

	column bucket
		dataType: string
		summarizeBy: none
		sourceColumn: bucket

	column appeals
		dataType: int64
		summarizeBy: sum
		sourceColumn: appeals

	column avg_tat
		dataType: double
		summarizeBy: sum
		sourceColumn: avg_tat

	column sla_pct
		dataType: double
		summarizeBy: sum
		sourceColumn: sla_pct

	measure 'Avg turnaround (days) (rework)' = AVERAGE ( 'rework'[avg_tat] )
		formatString: #,0.00
		displayFolder: Measures
		/// Avg turnaround (days) for the 'What rework costs' visual.

	measure 'SLA compliance % (rework)' = AVERAGE ( 'rework'[sla_pct] )
		formatString: #,0.00
		displayFolder: Measures
		/// SLA compliance % for the 'What rework costs' visual.

	partition rework = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExtractFolder & "\rework.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"bucket", type text},
				        {"appeals", Int64.Type},
				        {"avg_tat", type number},
				        {"sla_pct", type number}
				    })
				in
				    Typed
