table worst

	column Appeal_ID
		dataType: string
		summarizeBy: none
		sourceColumn: Appeal_ID

	column Appeal_Type
		dataType: string
		summarizeBy: none
		sourceColumn: Appeal_Type

	column Priority
		dataType: string
		summarizeBy: none
		sourceColumn: Priority

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status

	column Turnaround_Days
		dataType: double
		summarizeBy: sum
		sourceColumn: Turnaround_Days

	column Review_Wait_Days
		dataType: int64
		summarizeBy: sum
		sourceColumn: Review_Wait_Days

	column Reassignment_Count
		dataType: int64
		summarizeBy: sum
		sourceColumn: Reassignment_Count

	column Friction_Category
		dataType: string
		summarizeBy: none
		sourceColumn: Friction_Category

	partition worst = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExtractFolder & "\worst.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"Appeal_ID", type text},
				        {"Appeal_Type", type text},
				        {"Priority", type text},
				        {"Status", type text},
				        {"Turnaround_Days", type number},
				        {"Review_Wait_Days", Int64.Type},
				        {"Reassignment_Count", Int64.Type},
				        {"Friction_Category", type text}
				    })
				in
				    Typed
